/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImageData = IDL.Record({
  'contentType' : IDL.Text,
  'bytes' : IDL.Vec(IDL.Nat8),
});
export const CustomModule = IDL.Record({
  'moduleId' : IDL.Text,
  'title' : IDL.Text,
  'image' : ImageData,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserNameInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'fourCharId' : IDL.Text,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addContent2' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backendReset' : IDL.Func([], [], []),
  'createCustomModule' : IDL.Func([CustomModule], [], []),
  'deleteCustomModule' : IDL.Func([IDL.Text], [], []),
  'getAccessRequest' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'name' : IDL.Text, 'fourCharId' : IDL.Text })],
      [],
    ),
  'getAllUsersWithFullName' : IDL.Func([], [IDL.Vec(UserNameInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getContent2' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'greet' : IDL.Func([IDL.Text], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listCustomModules' : IDL.Func([], [IDL.Vec(CustomModule)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'requestApprovalWithName' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'name' : IDL.Text, 'fourCharId' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Record({ 'name' : IDL.Text })],
      [],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImageData = IDL.Record({
    'contentType' : IDL.Text,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const CustomModule = IDL.Record({
    'moduleId' : IDL.Text,
    'title' : IDL.Text,
    'image' : ImageData,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserNameInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'fourCharId' : IDL.Text,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addContent2' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backendReset' : IDL.Func([], [], []),
    'createCustomModule' : IDL.Func([CustomModule], [], []),
    'deleteCustomModule' : IDL.Func([IDL.Text], [], []),
    'getAccessRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'name' : IDL.Text, 'fourCharId' : IDL.Text })],
        [],
      ),
    'getAllUsersWithFullName' : IDL.Func(
        [],
        [IDL.Vec(UserNameInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getContent2' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'greet' : IDL.Func([IDL.Text], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listCustomModules' : IDL.Func([], [IDL.Vec(CustomModule)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'requestApprovalWithName' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'name' : IDL.Text, 'fourCharId' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Record({ 'name' : IDL.Text })],
        [],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };