/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CustomModule {
  'moduleId' : string,
  'title' : string,
  'image' : ImageData,
}
export interface ImageData { 'contentType' : string, 'bytes' : Uint8Array }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserNameInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
  'name' : string,
  'fourCharId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContent' : ActorMethod<[string, string], undefined>,
  'addContent2' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backendReset' : ActorMethod<[], undefined>,
  'createCustomModule' : ActorMethod<[CustomModule], undefined>,
  'deleteCustomModule' : ActorMethod<[string], undefined>,
  'getAccessRequest' : ActorMethod<
    [Principal],
    { 'name' : string, 'fourCharId' : string }
  >,
  'getAllUsersWithFullName' : ActorMethod<[], Array<UserNameInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [{ 'name' : string }]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[string], string>,
  'getContent2' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [{ 'name' : string }]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'greet' : ActorMethod<[string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listCustomModules' : ActorMethod<[], Array<CustomModule>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestApprovalWithName' : ActorMethod<
    [string],
    { 'name' : string, 'fourCharId' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[{ 'name' : string }], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];